### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by tesYolan** [Habush/service-result#2]
After running the service with the option.yaml and truncated.csv found in the test/data service as a client, going to the webpage provided yields the following error in the console

```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Access to fetch at 'http://30d1d7c6.ngrok.io/status/TGCJada' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
localhost/:1 Uncaught (in promise) TypeError: Failed to fetch
/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
content.min.js:2 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
```

I don't think this is hampering the result generation, but was wondering why is this happening when running in docker/client configuration as defined in your requirement file? 

What is the solution or am I missing sth that is rather trivial?

**Comment by Habush** [comment]
This issue is due to an invalid URL in the `utils.js` file that we were using for testing purpose. Remove it and it should work now. This [commit](https://github.com/Habush/service-result/commit/5706f984162a395a334be0003433e894dcc5d380) fixes the issue

**Comment by Habush** [comment]
Also, you need to empty the browser cache for the page. Otherwise, the changes won't take effect.

You can use the instructions [here](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/) to empty the cache and do a hard-reload
